---
- name: PowerDNS Master Slave and PowerDNS-Admin
  hosts: all
  become: true
  become_method: sudo
  vars_files:
    - all.yaml
  tasks:
    - name: Update and upgrade packages
      ansible.builtin.apt:
        upgrade: 'yes'
        state: present
        update_cache: true
        cache_valid_time: 86400

    - name: Install required packages
      ansible.builtin.apt:
        pkg:
          - net-tools
          - python3-pip
          - mysql-client
        state: present
        update_cache: true

    - name: Install pymysql python package
      ansible.builtin.pip:
        name: pymysql
        
    - name: Install and configure Docker
      ansible.builtin.import_tasks: 
        file: tasks/docker.yaml

    - name: Install and configure MariaDB
      ansible.builtin.import_tasks: 
        file: tasks/mariadb.yaml

    - name: Install and configure PowerDNS
      ansible.builtin.import_tasks: 
        file: tasks/pdns.yaml  

    - name: Install and configure PowerDNS-Admin
      ansible.builtin.import_tasks: 
        file: tasks/pdns-admin.yaml

    - name: Add zone and record
      ansible.builtin.import_tasks: 
        file: tasks/zone-record.yaml
...